-- AlterTable
ALTER TABLE "Company" ADD COLUMN     "isDemo" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "isDemo" BOOLEAN NOT NULL DEFAULT false;

-- Everything that exists today was generated by the seed, so it is sample data.
UPDATE "Company" SET "isDemo" = true;
UPDATE "Order" SET "isDemo" = true;
